name: Cypress project
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress.io
        uses: cypress-io/github-action@v5.0.2
      - name: Uploading artifact
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: index
          path: reports
          retention-days: 30 
      - name: Slack Notifications
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: teemo
          SLACK_TITLE: Execution Report
          SLACK_MESSAGE: "Te deixei um presentinho"
          SLACK_COLOR: ${{ job.status }}
      - name: Discord Notifier
        uses: fateyan/action-discord-notifier@v1.2.0
        with:
          webhook: https://discord.com/api/webhooks/1059904624435400744/lAx36O2RerBEr5o4zQrwzLpEaX1T0DmfnofgMUuBzkgiS-d6y-JIpom30GXhx5qTGFGK
          message-title:  A little gift
       
